version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: weekly
    time: '03:00'
    timezone: Europe/Berlin
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    time: '03:00'
    timezone: Europe/Berlin
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '03:00'
    timezone: Europe/Berlin
