dist: xenial
sudo: required
language: node_js
node_js:
  - '11'

addons:
  apt:
    packages:
      # for Cypress
      - libgconf-2-4

env:
  global:
    # run E2E tests against these values
    - REACT_APP_NODE_URI="https://nile.dev-ocean.com"
    - REACT_APP_AQUARIUS_URI="https://aquarius.nile.dev-ocean.com"
    - REACT_APP_BRIZO_URI="https://brizo.nile.dev-ocean.com"
    - REACT_APP_SECRET_STORE_URI="https://secret-store.nile.dev-ocean.com"
    - REACT_APP_FAUCET_URI="https://faucet.nile.dev-ocean.com"
    - REACT_APP_BRIZO_ADDRESS="0x376817c638d2a04f475a73af37f7b51a2862d567"

before_install:
  - npm install -g npm
  - npm install -g codacy-coverage truffle ganache-cli
  # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
  # https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

script:
  # - ./scripts/install.sh # runs automatically with npm ci
  - ./scripts/test.sh
  - ./scripts/coverage.sh
  - ./scripts/build.sh

notifications:
  email: false

cache:
  npm: true
  directories:
    # cache folder with Cypress binary
    - ~/.cache

deploy:
  - provider: script
    skip_cleanup: true
    script: bash -ex ./scripts/deploy_on_k8s.sh
    on:
      tags: true
      all_branches: true
