dist: xenial
language: node_js
node_js:
  - '11'

addons:
  apt:
    packages:
      # for Cypress
      - libgconf-2-4

before_install:
  - npm install -g npm
  - npm install -g codacy-coverage truffle ganache-cli

script:
  # - ./scripts/install.sh # runs automatically with npm ci
  # run E2E tests against these values
  - export REACT_APP_NODE_URI="https://pacific.oceanprotocol.com"
  - export REACT_APP_AQUARIUS_URI="https://aquarius.pacific.dev-ocean.com"
  - export REACT_APP_BRIZO_URI="https://brizo.pacific.dev-ocean.com"
  - export REACT_APP_SECRET_STORE_URI="https://secret-store.pacific.oceanprotocol.com"
  - export REACT_APP_FAUCET_URI="https://faucet.pacific.dev-ocean.com"
  - export REACT_APP_BRIZO_ADDRESS="0x008c25ed3594e094db4592f4115d5fa74c4f41ea"
  - export CYPRESS_NODE_URI=REACT_APP_NODE_URI
  - export CYPRESS_SEEDPHRASE="taxi music thumb unique chat sand crew more leg another off lamp"
  - export CYPRESS_CONSUME_ASSET="http://localhost:3000/asset/did:op:f5530ed7f4e3413db2dc223ab20e802c119ca24ac26d471497a4ac317fb6e667"
  - ./scripts/test.sh
  - ./scripts/coverage.sh
  - ./scripts/build.sh

notifications:
  email: false

cache:
  npm: true
  directories:
    # cache folder with Cypress binary
    - ~/.cache

deploy:
  - provider: script
    skip_cleanup: true
    script: bash -ex ./scripts/deploy_on_k8s.sh
    on:
      tags: true
      all_branches: true
