dist: xenial
language: node_js
node_js:
  - '11'

addons:
  apt:
    packages:
      # for Cypress
      - libgconf-2-4

before_install:
  - npm install -g npm
  - npm install -g codacy-coverage truffle ganache-cli

script:
  # - ./scripts/install.sh # runs automatically with npm ci
  # run E2E tests against these values
  - export REACT_APP_NODE_HOST="duero.dev-ocean.com"
  - export REACT_APP_AQUARIUS_HOST="aquarius.duero.dev-ocean.com"
  - export REACT_APP_BRIZO_HOST="brizo.duero.dev-ocean.com"
  - export REACT_APP_SECRET_STORE_HOST="secret-store.duero.dev-ocean.com"
  - export REACT_APP_FAUCET_HOST="faucet.duero.dev-ocean.com"
  - export REACT_APP_PARITY_HOST=$REACT_APP_NODE_HOST
  - export REACT_APP_BRIZO_ADDRESS="0x9d4ed58293f71122ad6a733c1603927a150735d0"
  - ./scripts/test.sh
  - ./scripts/coverage.sh
  - ./scripts/build.sh

notifications:
  email: false

cache:
  npm: true
  directories:
    # cache folder with Cypress binary
    - ~/.cache

deploy:
  - provider: script
    skip_cleanup: true
    script: bash -ex ./scripts/deploy_on_k8s.sh
    on:
      tags: true
      all_branches: true
