language: node_js
node_js: node

script:
  # - ./scripts/install.sh # runs automatically with npm ci
  - ./scripts/test.sh
  - ./scripts/build.sh

notifications:
  email: false

cache:
  directories:
    - node_modules
    - client/node_modules
    - server/node_modules

deploy:
  - provider: script
    skip_cleanup: true
    script: bash -ex ./scripts/deploy_on_k8s.sh
    on:
      tags: true
      all_branches: true
