dist: xenial
sudo: required
language: node_js
node_js:
  - '11'

services:
  - docker

addons:
  apt:
    packages:
      # for Cypress
      - libgconf-2-4

env:
  global:
    # run E2E tests against local Spree
    - REACT_APP_NODE_URI="http://localhost:8545"
    - REACT_APP_AQUARIUS_URI="http://localhost:5000"
    - REACT_APP_BRIZO_URI="http://localhost:8030"
    - REACT_APP_SECRET_STORE_URI="http://localhost:12001"
    - REACT_APP_FAUCET_URI="http://localhost:3001"
    - REACT_APP_BRIZO_ADDRESS="0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
    # start Barge with these versions
    - AQUARIUS_VERSION=v0.3.8
    - BRIZO_VERSION=v0.3.14
    - KEEPER_VERSION=v0.10.3
    - KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
    - FAUCET_VERSION=v0.2.4

before_install:
  - npm install -g npm
  - npm install -g codacy-coverage
  # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
  # https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

before_script:
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - bash -x start_ocean.sh --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..

script:
  # - ./scripts/install.sh # runs automatically with npm ci
  # executing `npm test` scripts individually here, so first one failing will exit the build
  - npm run lint || travis_terminate 1
  - ./scripts/test.sh || travis_terminate 1
  - ./scripts/coverage.sh
  - ./scripts/keeper.sh
  - npm run test:e2e || travis_terminate 1
  - ./scripts/build.sh

notifications:
  email: false

cache:
  npm: true
  directories:
    # cache folder with Cypress binary
    - ~/.cache

deploy:
  - provider: script
    skip_cleanup: true
    script: bash -ex ./scripts/deploy_on_k8s.sh
    on:
      tags: true
      all_branches: true
